import {StyleSheet, Dimensions} from 'react-native';
import { COLORS , FONTS, SIZES } from '../../constans';
const {height, width} = Dimensions.get('window');
export default StyleSheet.create({
  container: {
    backgroundColor: COLORS.primary,
    flex: 1,
  },
  innercontainer: {
    width: width * 0.94,
    alignSelf: 'center',
    backgroundColor: COLORS.white,
    marginVertical: height * 0.05,
    borderRadius: 20,
    marginTop: height * 0.14,
    marginBottom: height * 0.02,
    overflow: 'hidden',
  },
  heading: {
    color: COLORS.black,
    fontSize: width * 0.05,
    ...FONTS.sixHundred,
    alignSelf: 'center',
    marginTop: height * 0.025,
    fontWeight:'400'
  },
  subheading: {
    color: COLORS.black,
    fontSize: width * 0.036,
    ...FONTS.fiveHundred,
    alignSelf: 'center',
    marginBottom: height * 0.03,
  },
  btn: {
    marginTop: height * 0.04,
    alignSelf: 'center',
    width: width * 0.87,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'center',
  },
  donthaveaccount: {
    color: COLORS.black,
    fontSize: width * 0.031,
    ...FONTS.fiveHundred,
    alignSelf: 'center',
    marginTop: height * 0.01,
  },
  checktext: {
    color: COLORS.black,
    fontSize: width * 0.031,
    ...FONTS.fiveHundred,
    alignSelf: 'center',
    marginBottom: -3,
  },
  term: {
    color: COLORS.primary,
    fontSize: width * 0.031,
    ...FONTS.sixHundred,
    alignSelf: 'center',
    marginBottom: -3,
  },
  createone: {
    color: COLORS.primary,
    fontSize: width * 0.032,
    ...FONTS.sixHundred,
    alignSelf: 'center',
    marginTop: height * 0.01,
  },
  Resend: {
    color: COLORS.primary,
    fontSize: width * 0.032,
    ...FONTS.fiveHundred,
    marginRight: width * 0.03,
    alignSelf: 'flex-end',
    marginVertical: 3,
  },

  modalBox: {
    backgroundColor: COLORS.white,
    width: width * 0.9,
    paddingVertical: height * 0.03,
    paddingHorizontal: height * 0.02,
    borderRadius: 8,
  },
  resend: {
    fontSize: width * 0.031,
    fontFamily: FONTS.medium,
    color: COLORS.gray70,
    alignSelf: 'flex-end',
    textAlign: 'right',
  },
  time: {
    fontSize: width * 0.031,
    fontFamily: FONTS.medium,
    color: COLORS.primary,
    alignSelf: 'flex-end',
    textAlign: 'right',
  },

  otpCheck: {
    width: width * 0.68,
    height: height * 0.14,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  underlineStyleBase: {
    width: width * 0.13,
    height: width * 0.13,
    borderRadius: 12,
    color: COLORS.black,
    fontFamily: FONTS.semiBold,
    backgroundColor: COLORS.white,
    elevation: 4,
    fontSize: width * 0.04,
    paddingBottom: width * 0.015,
    borderWidth: 0,
    // paddingBottom: -0.1,
  },
  resent: {
    color: COLORS.primary,
    textDecorationLine: 'underline',
    fontSize: 14,
    ...FONTS.fiveHundred,
    alignSelf: 'flex-end',
    textAlign: 'right',
  },
  succesimg: {
    width: width * 0.9,
    alignSelf: 'center',
    height: height * 0.36,
    resizeMode: 'stretch',
    backgroundColor: COLORS.white,
    borderRadius: 10,
    overflow: 'hidden',
  },
  loginbtn:{
    color: COLORS.primary,
    fontSize: SIZES.width * 0.038,
    marginBottom: -3,
    marginLeft:SIZES.width*0.16,
    ...FONTS.sixHundred,
  },
  borderbtn: {
    width: width * 0.34,
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.primary,
    height: height * 0.05,
    elevation: 1,
  },
});
